#!/bin/bash

# Supabaseプロジェクト情報取得ガイド

echo "╔════════════════════════════════════════════════════════════════════╗"
echo "║                                                                    ║"
echo "║   📋 Supabase プロジェクト情報の取得方法                         ║"
echo "║                                                                    ║"
echo "╚════════════════════════════════════════════════════════════════════╝"
echo ""

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
RED='\033[0;31m'
NC='\033[0m'

echo -e "${BLUE}━━━ ステップ1: Supabase Dashboardにログイン ━━━${NC}"
echo ""
echo "  1. ブラウザで以下にアクセス:"
echo "     👉 https://supabase.com/dashboard"
echo ""
echo "  2. ログイン（まだの場合）"
echo ""
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

echo -e "${BLUE}━━━ ステップ2: プロジェクトを選択または作成 ━━━${NC}"
echo ""
echo "  【既存プロジェクトを使用する場合】"
echo "    - ダッシュボードから対象プロジェクトをクリック"
echo ""
echo "  【新規プロジェクトを作成する場合】"
echo "    1. 'New project' をクリック"
echo "    2. Organization: 選択または新規作成"
echo "    3. Name: 'ai-trader' など"
echo "    4. Database Password: 安全なパスワードを設定"
echo "    5. Region: Tokyo (Northeast Asia) を推奨"
echo "    6. 'Create new project' をクリック"
echo "    7. プロジェクト作成完了を待つ（1-2分）"
echo ""
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

echo -e "${BLUE}━━━ ステップ3: Project Reference ID を取得 ━━━${NC}"
echo ""
echo "  方法A: Settings ページから取得（推奨）"
echo "  ────────────────────────────────────"
echo "    1. 左サイドバーの ⚙️ 'Settings' をクリック"
echo "    2. 'General' タブを選択"
echo "    3. 'Reference ID' セクションを見つける"
echo "    4. コピーボタンをクリック"
echo ""
echo "    📍 直接アクセス:"
echo "       プロジェクト選択後、以下のURLにアクセス:"
echo "       https://supabase.com/dashboard/project/_/settings/general"
echo ""
echo "  方法B: URLから確認"
echo "  ────────────────────────────────────"
echo "    プロジェクトのダッシュボードURLを確認:"
echo "    https://supabase.com/dashboard/project/[YOUR_PROJECT_REF]/..."
echo "                                            ^^^^^^^^^^^^^^^^^^"
echo "                                            この16文字がProject ID"
echo ""
echo "  ${GREEN}形式:${NC} 16文字の英数字"
echo "  ${GREEN}例:${NC} abcdefghijklmnop"
echo ""
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

echo -e "${BLUE}━━━ ステップ4: その他の情報（参考）━━━${NC}"
echo ""
echo "  Project URL:"
echo "    Settings → API → Project URL"
echo "    形式: https://[PROJECT_REF].supabase.co"
echo ""
echo "  API Keys:"
echo "    Settings → API → Project API keys"
echo "    - anon/public key: フロントエンド用"
echo "    - service_role key: バックエンド用（機密情報）"
echo ""
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

echo -e "${YELLOW}━━━ ⚠️  重要な注意事項 ━━━${NC}"
echo ""
echo "  1. ${RED}service_role key は絶対に公開しないこと${NC}"
echo "  2. GitHub Secretsに設定する際は必ず正確にコピー"
echo "  3. プロジェクトを削除すると復元不可"
echo ""
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

echo -e "${GREEN}━━━ 📝 GitHub Secrets 設定内容（修正版）━━━${NC}"
echo ""
echo "  GitHub Actionsの制約により、Secret名を変更しました:"
echo ""
echo "  ${YELLOW}設定するSecret（3つ）:${NC}"
echo ""
echo "  1️⃣  Name: ${GREEN}SUPABASE_TOKEN${NC}"
echo "      Value: sbp_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
echo "      取得: https://supabase.com/dashboard/account/tokens"
echo ""
echo "  2️⃣  Name: ${GREEN}PROJECT_ID${NC}"
echo "      Value: 16文字の英数字（例: abcdefghijklmnop）"
echo "      取得: Settings → General → Reference ID"
echo ""
echo "  3️⃣  Name: ${GREEN}OPENAI_API_KEY${NC}"
echo "      Value: sk-proj-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
echo "      ※ Codespaces Secretsに設定済みのキー"
echo ""
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

echo -e "${GREEN}🔗 クイックリンク集${NC}"
echo ""
echo "  Supabase Dashboard:"
echo "    👉 https://supabase.com/dashboard"
echo ""
echo "  Access Token取得:"
echo "    👉 https://supabase.com/dashboard/account/tokens"
echo ""
echo "  GitHub Secrets設定:"
echo "    👉 https://github.com/ippeitanaka/ai-trader-supabase/settings/secrets/actions"
echo ""
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

# OpenAI API Key表示
echo -e "${GREEN}━━━ 🔑 OpenAI API Key確認 ━━━${NC}"
echo ""
if [ -f "/workspaces/.codespaces/shared/.env-secrets" ]; then
    API_KEY=$(grep OPENAI_API_KEY /workspaces/.codespaces/shared/.env-secrets | cut -d= -f2 | base64 -d 2>/dev/null)
    if [ -n "$API_KEY" ]; then
        echo "  ✅ Codespaces Secretsから検出:"
        echo "  ${API_KEY}"
        echo ""
        echo "  ${YELLOW}↑ この値を OPENAI_API_KEY としてGitHub Secretsに設定${NC}"
    else
        echo "  ❌ 検出できませんでした"
        echo "  手動でCodespaces Secretsから確認してください"
    fi
else
    echo "  ⚠️  Codespaces環境外のため自動検出できません"
fi
echo ""
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

echo -e "${GREEN}✅ 次のステップ${NC}"
echo ""
echo "  1. 上記の情報を収集"
echo "  2. GitHub Secretsページを開く"
echo "     👉 https://github.com/ippeitanaka/ai-trader-supabase/settings/secrets/actions"
echo "  3. 3つのSecretを設定"
echo "  4. GitHub Actionsを実行またはコードをプッシュ"
echo ""
