#!/bin/bash

# MT5 EA用の認証情報取得スクリプト

echo ""
echo "╔════════════════════════════════════════════════════════════════════╗"
echo "║                                                                    ║"
echo "║   🔑 MT5 EA 認証情報取得                                         ║"
echo "║                                                                    ║"
echo "╚════════════════════════════════════════════════════════════════════╝"
echo ""
echo "📋 MT5 EAに設定する認証情報"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "以下の情報をSupabase Dashboardから取得してください:"
echo ""
echo "👉 https://supabase.com/dashboard/project/nebphrnnpmuqbkymwefs/settings/api"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1️⃣ Project URL"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "   場所: Configuration → API Settings → Project URL"
echo ""
echo "   形式: https://nebphrnnpmuqbkymwefs.supabase.co"
echo ""
echo "   MT5 EA設定:"
echo "   SupabaseUrl = \"https://nebphrnnpmuqbkymwefs.supabase.co\""
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "2️⃣ Service Role Key (service_role secret)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "   場所: Configuration → API Settings → Project API keys"
echo "        → service_role (secret) の右側の \"Copy\" をクリック"
echo ""
echo "   ⚠️  注意: anon (public) ではなく service_role を使用"
echo ""
echo "   形式: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ..."
echo ""
echo "   MT5 EA設定:"
echo "   SupabaseApiKey = \"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ...\""
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "3️⃣ Edge Function URLs"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "   基本URL:"
echo "   https://nebphrnnpmuqbkymwefs.supabase.co/functions/v1"
echo ""
echo "   各関数のエンドポイント:"
echo ""
echo "   • AI Trader (メイン):"
echo "     https://nebphrnnpmuqbkymwefs.supabase.co/functions/v1/ai-trader"
echo ""
echo "   • EA Log (ログ記録):"
echo "     https://nebphrnnpmuqbkymwefs.supabase.co/functions/v1/ea-log"
echo ""
echo "   • AI Signals (シグナル取得):"
echo "     https://nebphrnnpmuqbkymwefs.supabase.co/functions/v1/ai-signals"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📝 MT5 EAファイルの場所"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "   このワークスペース内:"
echo "   mt5/AI_QuadFusion_EA.mq5"
echo ""
echo "   MT5にコピーする場所:"
echo "   C:\\Users\\[ユーザー名]\\AppData\\Roaming\\MetaQuotes\\Terminal\\"
echo "   [ターミナルID]\\MQL5\\Experts\\AI_QuadFusion_EA.mq5"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🔧 次のステップ"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Supabase Dashboardを開いて認証情報をコピー"
echo "   👉 https://supabase.com/dashboard/project/nebphrnnpmuqbkymwefs/settings/api"
echo ""
echo "2. MT5 EAファイルを開いて以下の部分を編集:"
echo ""
echo "   // Supabase設定"
echo "   input string SupabaseUrl = \"https://nebphrnnpmuqbkymwefs.supabase.co\";"
echo "   input string SupabaseApiKey = \"[Service Role Keyをここに貼り付け]\";"
echo ""
echo "3. MT5 EAをコンパイル"
echo ""
echo "4. デモ口座でテスト実行"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "認証情報を取得したら教えてください！"
echo "MT5 EAファイルの設定方法を詳しく説明します 🚀"
echo ""
