#!/bin/bash

# ===================================================================
# 勝率改善チェックスクリプト
# SMA200/800実装前後の勝率を比較
# ===================================================================

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📊 トレード戦歴分析"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Supabase設定（プロジェクトURLを環境変数から取得）
PROJECT_REF="nebphrnnpmuqbkymwefs"
PROJECT_URL="https://${PROJECT_REF}.supabase.co"

echo "🔍 Supabaseプロジェクトに接続中..."
echo "   URL: ${PROJECT_URL}"
echo ""

# PostgreSQLに直接接続してデータ取得
echo "📋 完了した取引の統計を取得中..."
echo ""

# SQL クエリを実行（RLSを回避するためサービスロールキーが必要）
# ここではローカルSupabaseを想定した代替方法を使用

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📈 全期間の取引統計"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "以下のSQLをSupabase Dashboardで実行してください："
echo ""
echo "SELECT"
echo "  COUNT(*) FILTER (WHERE actual_result = 'WIN') as wins,"
echo "  COUNT(*) FILTER (WHERE actual_result = 'LOSS') as losses,"
echo "  COUNT(*) FILTER (WHERE actual_result IN ('WIN', 'LOSS')) as total_completed,"
echo "  ROUND(100.0 * COUNT(*) FILTER (WHERE actual_result = 'WIN') / "
echo "        NULLIF(COUNT(*) FILTER (WHERE actual_result IN ('WIN', 'LOSS')), 0), 2) as win_rate,"
echo "  ROUND(AVG(profit_loss) FILTER (WHERE actual_result = 'WIN'), 2) as avg_win,"
echo "  ROUND(AVG(profit_loss) FILTER (WHERE actual_result = 'LOSS'), 2) as avg_loss,"
echo "  ROUND(SUM(profit_loss), 2) as total_profit"
echo "FROM ai_signals"
echo "WHERE actual_result IN ('WIN', 'LOSS');"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📅 最近7日間の統計："
echo ""
echo "SELECT"
echo "  COUNT(*) FILTER (WHERE actual_result = 'WIN') as wins,"
echo "  COUNT(*) FILTER (WHERE actual_result = 'LOSS') as losses,"
echo "  COUNT(*) FILTER (WHERE actual_result IN ('WIN', 'LOSS')) as total_completed,"
echo "  ROUND(100.0 * COUNT(*) FILTER (WHERE actual_result = 'WIN') / "
echo "        NULLIF(COUNT(*) FILTER (WHERE actual_result IN ('WIN', 'LOSS')), 0), 2) as win_rate"
echo "FROM ai_signals"
echo "WHERE actual_result IN ('WIN', 'LOSS')"
echo "  AND created_at >= NOW() - INTERVAL '7 days';"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📊 SMA200/800実装後の統計（10/26以降）："
echo ""
echo "SELECT"
echo "  COUNT(*) FILTER (WHERE actual_result = 'WIN') as wins,"
echo "  COUNT(*) FILTER (WHERE actual_result = 'LOSS') as losses,"
echo "  COUNT(*) FILTER (WHERE actual_result IN ('WIN', 'LOSS')) as total_completed,"
echo "  ROUND(100.0 * COUNT(*) FILTER (WHERE actual_result = 'WIN') / "
echo "        NULLIF(COUNT(*) FILTER (WHERE actual_result IN ('WIN', 'LOSS')), 0), 2) as win_rate"
echo "FROM ai_signals"
echo "WHERE actual_result IN ('WIN', 'LOSS')"
echo "  AND created_at >= '2025-10-26';"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🔎 最新20件の取引詳細："
echo ""
echo "SELECT"
echo "  created_at,"
echo "  symbol,"
echo "  dir,"
echo "  win_prob,"
echo "  actual_result,"
echo "  profit_loss,"
echo "  entry_price,"
echo "  exit_price"
echo "FROM ai_signals"
echo "WHERE actual_result IN ('WIN', 'LOSS')"
echo "ORDER BY created_at DESC"
echo "LIMIT 20;"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📍 Supabase Dashboardへのアクセス："
echo "   https://supabase.com/dashboard/project/${PROJECT_REF}/editor"
echo ""
echo "左メニュー「SQL Editor」を開いて、上記のSQLを実行してください。"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
