-- Restore the runtime contract when historical migrations are recorded but the
-- table is absent. Do not seed legacy thresholds: an empty table intentionally
-- preserves strategy defaults, environment values and EA runtime overrides.
CREATE TABLE IF NOT EXISTS public.ai_config (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  instance text,
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE public.ai_config
  ADD COLUMN IF NOT EXISTS instance text,
  ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now(),
  ADD COLUMN IF NOT EXISTS min_win_prob double precision,
  ADD COLUMN IF NOT EXISTS reward_rr double precision,
  ADD COLUMN IF NOT EXISTS risk_atr_mult double precision,
  ADD COLUMN IF NOT EXISTS max_cost_r double precision,
  ADD COLUMN IF NOT EXISTS direction_horizon_minutes integer,
  ADD COLUMN IF NOT EXISTS max_hold_minutes integer,
  ADD COLUMN IF NOT EXISTS pending_expiry_min integer;

CREATE UNIQUE INDEX IF NOT EXISTS idx_ai_config_instance ON public.ai_config (instance);
ALTER TABLE public.ai_config ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.ai_config FROM anon, authenticated;
GRANT SELECT ON TABLE public.ai_config TO service_role;
COMMENT ON TABLE public.ai_config IS
  'Optional per-instance runtime overrides. Missing rows/null values inherit application defaults; no browser access.';
NOTIFY pgrst, 'reload schema';
