-- Store the daily AI trading plan generated by pair-selector.
-- The plan is intentionally JSONB so the EA / dashboard can evolve without
-- requiring a migration for every new decision field.

ALTER TABLE public.pair_selection_reports
  ADD COLUMN IF NOT EXISTS trade_plan JSONB NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS plan_overrides JSONB NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS plan_status TEXT NOT NULL DEFAULT 'active';

CREATE INDEX IF NOT EXISTS idx_pair_selection_reports_plan_status_created_at
  ON public.pair_selection_reports (plan_status, created_at DESC);

COMMENT ON COLUMN public.pair_selection_reports.trade_plan IS
  'Daily AI trading plan: allowed direction, strategy, sessions, event windows, and dynamic execution gates.';

COMMENT ON COLUMN public.pair_selection_reports.plan_overrides IS
  'Manual dashboard overrides for the active daily trade plan.';

COMMENT ON COLUMN public.pair_selection_reports.plan_status IS
  'Daily plan runtime status such as active or paused.';

ALTER TABLE public.ai_signals
  ADD COLUMN IF NOT EXISTS trade_plan_id BIGINT NULL REFERENCES public.pair_selection_reports(id),
  ADD COLUMN IF NOT EXISTS plan_alignment TEXT NULL,
  ADD COLUMN IF NOT EXISTS event_risk TEXT NULL,
  ADD COLUMN IF NOT EXISTS market_session TEXT NULL,
  ADD COLUMN IF NOT EXISTS utc_hour INTEGER NULL,
  ADD COLUMN IF NOT EXISTS day_of_week INTEGER NULL,
  ADD COLUMN IF NOT EXISTS htf_context JSONB NULL,
  ADD COLUMN IF NOT EXISTS level_distances JSONB NULL,
  ADD COLUMN IF NOT EXISTS chart_structure JSONB NULL,
  ADD COLUMN IF NOT EXISTS volatility_context JSONB NULL,
  ADD COLUMN IF NOT EXISTS cost_context JSONB NULL;

CREATE INDEX IF NOT EXISTS idx_ai_signals_trade_plan_id
  ON public.ai_signals (trade_plan_id)
  WHERE trade_plan_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_ai_signals_market_session
  ON public.ai_signals (market_session)
  WHERE market_session IS NOT NULL;

COMMENT ON COLUMN public.ai_signals.trade_plan_id IS
  'pair_selection_reports.id used by ai-trader at decision time.';

COMMENT ON COLUMN public.ai_signals.plan_alignment IS
  'How the entry aligned with the daily trade plan.';

COMMENT ON COLUMN public.ai_signals.event_risk IS
  'Event-risk classification applied at decision time.';

COMMENT ON COLUMN public.ai_signals.htf_context IS
  'Higher-timeframe technical context sent by the EA.';

COMMENT ON COLUMN public.ai_signals.level_distances IS
  'Distances to prior/current session levels sent by the EA.';

COMMENT ON COLUMN public.ai_signals.chart_structure IS
  'Swing structure, breakout direction, and support/resistance distance context sent by the EA.';

COMMENT ON COLUMN public.ai_signals.volatility_context IS
  'Relative volatility context such as ATR percentile and range expansion sent by the EA.';

COMMENT ON COLUMN public.ai_signals.cost_context IS
  'Execution cost context such as spread-to-ATR and tick-volume ratio sent by the EA.';

ALTER TABLE public."ea-log"
  ADD COLUMN IF NOT EXISTS trade_plan_id BIGINT NULL REFERENCES public.pair_selection_reports(id),
  ADD COLUMN IF NOT EXISTS plan_alignment TEXT NULL,
  ADD COLUMN IF NOT EXISTS event_risk TEXT NULL,
  ADD COLUMN IF NOT EXISTS market_session TEXT NULL;

CREATE INDEX IF NOT EXISTS idx_ea_log_trade_plan_id
  ON public."ea-log" (trade_plan_id)
  WHERE trade_plan_id IS NOT NULL;
