name: Deploy Supabase Function

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}   # 手動実行ボタンを出す

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4



      - uses: supabase/setup-cli@v1
        with:
          version: 2.45.5

      - name: Deploy edge function
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: supabase functions deploy ai-trader --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}
