name: healthcheck

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"

permissions:
  contents: read
  issues: write

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo "ok"
